### ISSUE TITLE
模糊搜索结果有bug

### ISSUE THREAD

**Issue by zpfbuaa** [BSchain/BSC#18]
## 模糊搜索bug
- [ ] 购买数据页面
- [ ] 历史订单页面
- [ ] 我的数据页面
- [ ] 区块链信息页面

> 需要解决function.py中的搜索代码

**Comment by jasonlovescoding** [comment]
什么样的bug？能不能描述一下

**Comment by zpfbuaa** [comment]
按照数据名搜索(由于模糊匹配，使用的关键字为sql中的like)
假设搜索的结果有20条，那么搜索结果就会分页；
但是点击搜索结果的其他页码时，页面显示的不是搜索的结果；

**Comment by zpfbuaa** [comment]
2018年03月28日 today fix this bug
